# Generated by Django 5.0.2 on 2024-03-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.government')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.center')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.government')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('Gender', models.CharField(max_length=5)),
                ('level', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('current_capacity', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.center')),
                ('governnment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.government')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.village')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('specilization', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.center')),
                ('governnment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.government')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.village')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.center')),
                ('governnment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.government')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.village')),
            ],
        ),
        migrations.CreateModel(
            name='Holly_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.center')),
                ('governnment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.government')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorest.village')),
            ],
        ),
    ]
