# Generated by Django 5.0.2 on 2024-03-06 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0002_government_center_village_school_medical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holly_places',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medical',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='popualtion',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medical',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
