# Generated by Django 5.0.2 on 2024-03-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0003_holly_places_capacity_infrastructure_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holly_places',
            old_name='governnment',
            new_name='government',
        ),
        migrations.RenameField(
            model_name='infrastructure',
            old_name='governnment',
            new_name='government',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='governnment',
            new_name='government',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='governnment',
            new_name='government',
        ),
    ]
