# Generated by Django 5.0.2 on 2024-03-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0005_holly_places_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holly_places',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='school',
            name='availability',
        ),
    ]
