# Generated by Django 5.0.2 on 2024-03-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0006_remove_holly_places_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='popualtion',
            new_name='popualation',
        ),
    ]
