# Generated by Django 5.0.2 on 2024-03-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0007_rename_popualtion_village_popualation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='popualation',
            new_name='population',
        ),
    ]
