# Generated by Django 5.0.2 on 2024-03-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0009_public_safety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='specilization',
            new_name='specialization',
        ),
    ]
