# Generated by Django 5.0.2 on 2024-03-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0012_holly_places_type_village_rating_alter_school_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('electricity', 'electricity'), ('sewer', 'sewer'), ('water', 'water'), ('gas', 'gas'), ('landline', 'landline')], default='unknown', max_length=20),
        ),
    ]
