# Generated by Django 5.0.2 on 2024-03-10 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0017_alter_public_safety_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_safety',
            name='village',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='poorest.village'),
        ),
    ]
