# Generated by Django 5.0.2 on 2024-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorest', '0018_alter_public_safety_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='population',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='government',
            name='population',
            field=models.BigIntegerField(default=0),
        ),
    ]
